spring.application.name=Spring_Security

server.port=8080

# Added 'security_db' and the auto-create flag to the URL
spring.datasource.url=jdbc:mysql://localhost:3306/security_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
